/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Medicine {
  'id' : string,
  'finalPrice' : bigint,
  'cost' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isFree' : boolean,
  'availability' : MedicineAvailability,
  'imageUrl' : string,
  'senderName' : string,
  'discount' : bigint,
  'paymentMode' : PaymentMode,
  'locationAddress' : string,
  'senderId' : Principal,
}
export type MedicineAvailability = { 'outOfStock' : null } |
  { 'available' : null };
export interface OrderRecord {
  'id' : string,
  'finalPrice' : bigint,
  'customerName' : string,
  'status' : string,
  'paymentStatus' : PaymentStatus,
  'originalCost' : bigint,
  'discountAmount' : bigint,
  'createdAt' : Time,
  'paymentMode' : PaymentMode,
  'customerId' : Principal,
  'discountPercentage' : bigint,
  'medicineId' : string,
  'senderId' : Principal,
  'medicineName' : string,
}
export type PaymentMode = { 'both' : null } |
  { 'offline' : null } |
  { 'online' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'customer' : null } |
  { 'sender' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  /**
   * / Create a new user profile for the caller. Requires authentication.
   */
  'createUser' : ActorMethod<
    [string, string, UserRole, string, string],
    UserProfile
  >,
  /**
   * / Delete a medicine listing. Caller must own the listing.
   */
  'deleteMedicine' : ActorMethod<[string], undefined>,
  /**
   * / List all medicines (unfiltered). Admin only.
   */
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  /**
   * / List all medicines sorted by cost. Public – no authentication required.
   */
  'getAllMedicinesByCost' : ActorMethod<[], Array<Medicine>>,
  /**
   * / List all medicines sorted by name. Public – no authentication required.
   */
  'getAllMedicinesByName' : ActorMethod<[], Array<Medicine>>,
  /**
   * / List all orders (unfiltered). Admin only.
   */
  'getAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  /**
   * / List all registered users. Admin only.
   */
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / Return the access-control role of the caller. Public – no authentication required.
   */
  'getCallerAccessRole' : ActorMethod<[], UserRole__1>,
  /**
   * / Get the calling user's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  /**
   * / Get the current authenticated user's profile (non-optional, traps if missing).
   */
  'getCurrentUser' : ActorMethod<[], UserProfile>,
  /**
   * / List all orders placed by the calling customer.
   */
  'getCustomerOrders' : ActorMethod<[], Array<OrderRecord>>,
  /**
   * / Get a medicine by ID. Public – no authentication required.
   */
  'getMedicineById' : ActorMethod<[string], Medicine>,
  /**
   * / Get an order by ID. Only the customer or sender involved, or an admin, may view it.
   */
  'getOrderById' : ActorMethod<[string], OrderRecord>,
  /**
   * / List all medicines uploaded by the calling sender. Requires authentication.
   */
  'getSenderMedicines' : ActorMethod<[], Array<Medicine>>,
  /**
   * / List all orders received by the calling sender.
   */
  'getSenderOrders' : ActorMethod<[], Array<OrderRecord>>,
  /**
   * / Fetch any user by principal. Only the user themselves or an admin may call this.
   */
  'getUserById' : ActorMethod<[Principal], UserProfile>,
  /**
   * / List users filtered by application role. Admin only.
   */
  'getUserByRole' : ActorMethod<[UserRole], Array<UserProfile>>,
  /**
   * / Fetch another user's profile. Callers may only view their own profile
   * / unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Place an order for a medicine. Caller must be an authenticated user (customer).
   */
  'placeOrder' : ActorMethod<[string, string, PaymentMode], OrderRecord>,
  /**
   * / Save / update the calling user's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update a medicine listing. Caller must own the listing.
   */
  'updateMedicine' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      MedicineAvailability,
      PaymentMode,
      string,
      string,
    ],
    Medicine
  >,
  /**
   * / Update an order's status. Only the sender of the order or an admin may do this.
   */
  'updateOrderStatus' : ActorMethod<
    [string, string, PaymentStatus],
    OrderRecord
  >,
  /**
   * / Update the calling user's own profile fields.
   */
  'updateUserProfile' : ActorMethod<
    [string, string, string, string],
    UserProfile
  >,
  /**
   * / Upload a new medicine listing. Caller must be an authenticated user (sender).
   */
  'uploadMedicine' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      MedicineAvailability,
      PaymentMode,
      string,
      string,
    ],
    Medicine
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];