/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'customer' : IDL.Null,
  'sender' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const MedicineAvailability = IDL.Variant({
  'outOfStock' : IDL.Null,
  'available' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'both' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'finalPrice' : IDL.Nat,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'availability' : MedicineAvailability,
  'imageUrl' : IDL.Text,
  'senderName' : IDL.Text,
  'discount' : IDL.Nat,
  'paymentMode' : PaymentMode,
  'locationAddress' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Text,
  'finalPrice' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'originalCost' : IDL.Nat,
  'discountAmount' : IDL.Nat,
  'createdAt' : Time,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Principal,
  'discountPercentage' : IDL.Nat,
  'medicineId' : IDL.Text,
  'senderId' : IDL.Principal,
  'medicineName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllMedicinesByCost' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllMedicinesByName' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerAccessRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCurrentUser' : IDL.Func([], [UserProfile], ['query']),
  'getCustomerOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getMedicineById' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [OrderRecord], ['query']),
  'getSenderMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getSenderOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getUserById' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserByRole' : IDL.Func([UserRole], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, PaymentMode], [OrderRecord], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        MedicineAvailability,
        PaymentMode,
        IDL.Text,
        IDL.Text,
      ],
      [Medicine],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Text, PaymentStatus],
      [OrderRecord],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'uploadMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        MedicineAvailability,
        PaymentMode,
        IDL.Text,
        IDL.Text,
      ],
      [Medicine],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'customer' : IDL.Null, 'sender' : IDL.Null });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MedicineAvailability = IDL.Variant({
    'outOfStock' : IDL.Null,
    'available' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({
    'both' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'finalPrice' : IDL.Nat,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'availability' : MedicineAvailability,
    'imageUrl' : IDL.Text,
    'senderName' : IDL.Text,
    'discount' : IDL.Nat,
    'paymentMode' : PaymentMode,
    'locationAddress' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Text,
    'finalPrice' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'originalCost' : IDL.Nat,
    'discountAmount' : IDL.Nat,
    'createdAt' : Time,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Principal,
    'discountPercentage' : IDL.Nat,
    'medicineId' : IDL.Text,
    'senderId' : IDL.Principal,
    'medicineName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllMedicinesByCost' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllMedicinesByName' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerAccessRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCurrentUser' : IDL.Func([], [UserProfile], ['query']),
    'getCustomerOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getMedicineById' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [OrderRecord], ['query']),
    'getSenderMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getSenderOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getUserById' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserByRole' : IDL.Func([UserRole], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, PaymentMode],
        [OrderRecord],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          MedicineAvailability,
          PaymentMode,
          IDL.Text,
          IDL.Text,
        ],
        [Medicine],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text, PaymentStatus],
        [OrderRecord],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'uploadMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          MedicineAvailability,
          PaymentMode,
          IDL.Text,
          IDL.Text,
        ],
        [Medicine],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };