/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface OrderRecord {
    id: string;
    finalPrice: bigint;
    customerName: string;
    status: string;
    paymentStatus: PaymentStatus;
    originalCost: bigint;
    discountAmount: bigint;
    createdAt: Time;
    paymentMode: PaymentMode;
    customerId: Principal;
    discountPercentage: bigint;
    medicineId: string;
    senderId: Principal;
    medicineName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Medicine {
    id: string;
    finalPrice: bigint;
    cost: bigint;
    name: string;
    createdAt: Time;
    description: string;
    isFree: boolean;
    availability: MedicineAvailability;
    imageUrl: string;
    senderName: string;
    discount: bigint;
    paymentMode: PaymentMode;
    locationAddress: string;
    senderId: Principal;
}
export interface UserProfile {
    id: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    email: string;
    address: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MedicineAvailability {
    outOfStock = "outOfStock",
    available = "available"
}
export enum PaymentMode {
    both = "both",
    offline = "offline",
    online = "online"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid"
}
export enum UserRole {
    customer = "customer",
    sender = "sender"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    /**
     * / Create a new user profile for the caller. Requires authentication.
     */
    createUser(name: string, email: string, role: UserRole, phone: string, address: string): Promise<UserProfile>;
    /**
     * / Delete a medicine listing. Caller must own the listing.
     */
    deleteMedicine(medicineId: string): Promise<void>;
    /**
     * / List all medicines (unfiltered). Admin only.
     */
    getAllMedicines(): Promise<Array<Medicine>>;
    /**
     * / List all medicines sorted by cost. Public – no authentication required.
     */
    getAllMedicinesByCost(): Promise<Array<Medicine>>;
    /**
     * / List all medicines sorted by name. Public – no authentication required.
     */
    getAllMedicinesByName(): Promise<Array<Medicine>>;
    /**
     * / List all orders (unfiltered). Admin only.
     */
    getAllOrders(): Promise<Array<OrderRecord>>;
    /**
     * / List all registered users. Admin only.
     */
    getAllUsers(): Promise<Array<UserProfile>>;
    /**
     * / Return the access-control role of the caller. Public – no authentication required.
     */
    getCallerAccessRole(): Promise<UserRole__1>;
    /**
     * / Get the calling user's own profile.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    /**
     * / Get the current authenticated user's profile (non-optional, traps if missing).
     */
    getCurrentUser(): Promise<UserProfile>;
    /**
     * / List all orders placed by the calling customer.
     */
    getCustomerOrders(): Promise<Array<OrderRecord>>;
    /**
     * / Get a medicine by ID. Public – no authentication required.
     */
    getMedicineById(medicineId: string): Promise<Medicine>;
    /**
     * / Get an order by ID. Only the customer or sender involved, or an admin, may view it.
     */
    getOrderById(orderId: string): Promise<OrderRecord>;
    /**
     * / List all medicines uploaded by the calling sender. Requires authentication.
     */
    getSenderMedicines(): Promise<Array<Medicine>>;
    /**
     * / List all orders received by the calling sender.
     */
    getSenderOrders(): Promise<Array<OrderRecord>>;
    /**
     * / Fetch any user by principal. Only the user themselves or an admin may call this.
     */
    getUserById(userId: Principal): Promise<UserProfile>;
    /**
     * / List users filtered by application role. Admin only.
     */
    getUserByRole(role: UserRole): Promise<Array<UserProfile>>;
    /**
     * / Fetch another user's profile. Callers may only view their own profile
     * / unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Place an order for a medicine. Caller must be an authenticated user (customer).
     */
    placeOrder(medicineId: string, customerName: string, paymentMode: PaymentMode): Promise<OrderRecord>;
    /**
     * / Save / update the calling user's own profile.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Update a medicine listing. Caller must own the listing.
     */
    updateMedicine(medicineId: string, name: string, description: string, cost: bigint, discount: bigint, availability: MedicineAvailability, paymentMode: PaymentMode, imageUrl: string, locationAddress: string): Promise<Medicine>;
    /**
     * / Update an order's status. Only the sender of the order or an admin may do this.
     */
    updateOrderStatus(orderId: string, status: string, paymentStatus: PaymentStatus): Promise<OrderRecord>;
    /**
     * / Update the calling user's own profile fields.
     */
    updateUserProfile(name: string, email: string, phone: string, address: string): Promise<UserProfile>;
    /**
     * / Upload a new medicine listing. Caller must be an authenticated user (sender).
     */
    uploadMedicine(senderName: string, medicineName: string, description: string, cost: bigint, discount: bigint, availability: MedicineAvailability, paymentMode: PaymentMode, imageUrl: string, locationAddress: string): Promise<Medicine>;
}
import type { Medicine as _Medicine, MedicineAvailability as _MedicineAvailability, OrderRecord as _OrderRecord, PaymentMode as _PaymentMode, PaymentStatus as _PaymentStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: UserRole, arg3: string, arg4: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMedicine(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getAllMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedicinesByCost(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicinesByCost();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicinesByCost();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedicinesByName(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicinesByName();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicinesByName();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAccessRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAccessRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAccessRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrders(): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicineById(arg0: string): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicineById(arg0);
                return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicineById(arg0);
            return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<OrderRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSenderMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSenderMedicines();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSenderMedicines();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSenderOrders(): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSenderOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSenderOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByRole(arg0: UserRole): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByRole(to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByRole(to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: PaymentMode): Promise<OrderRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg2));
                return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg2));
            return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMedicine(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: MedicineAvailability, arg6: PaymentMode, arg7: string, arg8: string): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_MedicineAvailability_n36(this._uploadFile, this._downloadFile, arg5), to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_MedicineAvailability_n36(this._uploadFile, this._downloadFile, arg5), to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: string, arg1: string, arg2: PaymentStatus): Promise<OrderRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_PaymentStatus_n38(this._uploadFile, this._downloadFile, arg2));
                return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_PaymentStatus_n38(this._uploadFile, this._downloadFile, arg2));
            return from_candid_OrderRecord_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3);
                return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3);
            return from_candid_UserProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadMedicine(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: MedicineAvailability, arg6: PaymentMode, arg7: string, arg8: string): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_MedicineAvailability_n36(this._uploadFile, this._downloadFile, arg5), to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_MedicineAvailability_n36(this._uploadFile, this._downloadFile, arg5), to_candid_PaymentMode_n32(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return from_candid_Medicine_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MedicineAvailability_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicineAvailability): MedicineAvailability {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Medicine_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medicine): Medicine {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderRecord_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderRecord): OrderRecord {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    email: string;
    address: string;
    phone: string;
}): {
    id: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    email: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    finalPrice: bigint;
    cost: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    isFree: boolean;
    availability: _MedicineAvailability;
    imageUrl: string;
    senderName: string;
    discount: bigint;
    paymentMode: _PaymentMode;
    locationAddress: string;
    senderId: Principal;
}): {
    id: string;
    finalPrice: bigint;
    cost: bigint;
    name: string;
    createdAt: Time;
    description: string;
    isFree: boolean;
    availability: MedicineAvailability;
    imageUrl: string;
    senderName: string;
    discount: bigint;
    paymentMode: PaymentMode;
    locationAddress: string;
    senderId: Principal;
} {
    return {
        id: value.id,
        finalPrice: value.finalPrice,
        cost: value.cost,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isFree: value.isFree,
        availability: from_candid_MedicineAvailability_n19(_uploadFile, _downloadFile, value.availability),
        imageUrl: value.imageUrl,
        senderName: value.senderName,
        discount: value.discount,
        paymentMode: from_candid_PaymentMode_n21(_uploadFile, _downloadFile, value.paymentMode),
        locationAddress: value.locationAddress,
        senderId: value.senderId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    finalPrice: bigint;
    customerName: string;
    status: string;
    paymentStatus: _PaymentStatus;
    originalCost: bigint;
    discountAmount: bigint;
    createdAt: _Time;
    paymentMode: _PaymentMode;
    customerId: Principal;
    discountPercentage: bigint;
    medicineId: string;
    senderId: Principal;
    medicineName: string;
}): {
    id: string;
    finalPrice: bigint;
    customerName: string;
    status: string;
    paymentStatus: PaymentStatus;
    originalCost: bigint;
    discountAmount: bigint;
    createdAt: Time;
    paymentMode: PaymentMode;
    customerId: Principal;
    discountPercentage: bigint;
    medicineId: string;
    senderId: Principal;
    medicineName: string;
} {
    return {
        id: value.id,
        finalPrice: value.finalPrice,
        customerName: value.customerName,
        status: value.status,
        paymentStatus: from_candid_PaymentStatus_n26(_uploadFile, _downloadFile, value.paymentStatus),
        originalCost: value.originalCost,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        paymentMode: from_candid_PaymentMode_n21(_uploadFile, _downloadFile, value.paymentMode),
        customerId: value.customerId,
        discountPercentage: value.discountPercentage,
        medicineId: value.medicineId,
        senderId: value.senderId,
        medicineName: value.medicineName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    sender: null;
}): UserRole {
    return "customer" in value ? UserRole.customer : "sender" in value ? UserRole.sender : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outOfStock: null;
} | {
    available: null;
}): MedicineAvailability {
    return "outOfStock" in value ? MedicineAvailability.outOfStock : "available" in value ? MedicineAvailability.available : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    offline: null;
} | {
    online: null;
}): PaymentMode {
    return "both" in value ? PaymentMode.both : "offline" in value ? PaymentMode.offline : "online" in value ? PaymentMode.online : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medicine>): Array<Medicine> {
    return value.map((x)=>from_candid_Medicine_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderRecord>): Array<OrderRecord> {
    return value.map((x)=>from_candid_OrderRecord_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n12(_uploadFile, _downloadFile, x));
}
function to_candid_MedicineAvailability_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicineAvailability): _MedicineAvailability {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    email: string;
    address: string;
    phone: string;
}): {
    id: Principal;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    email: string;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    customer: null;
} | {
    sender: null;
} {
    return value == UserRole.customer ? {
        customer: null
    } : value == UserRole.sender ? {
        sender: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    both: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == PaymentMode.both ? {
        both: null
    } : value == PaymentMode.offline ? {
        offline: null
    } : value == PaymentMode.online ? {
        online: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicineAvailability): {
    outOfStock: null;
} | {
    available: null;
} {
    return value == MedicineAvailability.outOfStock ? {
        outOfStock: null
    } : value == MedicineAvailability.available ? {
        available: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
